# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development: &DEV
  adapter: mysql2
  database: <%= ENV["SIMFY_DB"] || "simfy_development" %>
  username: simfy
  encoding: utf8
  
  
test: &TEST
  adapter: mysql2
  database: simfy_test<%= ["", ENV["TEST_DB"]].compact.join("_") %><%= ENV['TEST_ENV_NUMBER'] %>
  username: simfy
  encoding: utf8
  

production: &PRODUCTION
  adapter: mysql2
  database: simfy_live
  username: simfy_rails
  encoding: utf8
  host: mysql-master.o2
  port: 3306
  
production_slave:
  <<: *PRODUCTION
  username: live_readonly
  host: mysql-slave.o2

staging: &STAGING
  adapter: mysql2
  database: simfy_live
  username: simfy_staging
  password: Pei8ERu4
  encoding: utf8
  host: localhost
  port: 3306

staging_slave:
  <<: *STAGING